-- 권한 테이블
CREATE TABLE AUTHORITIES (
    AUTHORITY VARCHAR2(50) DEFAULT 'ROLE_USER' NOT NULL, -- 권한 (기본값 설정)
    USER_NO NUMBER NOT NULL,                            -- 사용자 번호 (PK 대상)
    
    CONSTRAINT PK_AUTHORITIES PRIMARY KEY (USER_NO)
);

-- 사용자 테이블
CREATE TABLE "USER" (
    USER_NO NUMBER NOT NULL,                   -- 사용자 계정 번호(PK)
    USER_NAME VARCHAR2(100) NOT NULL,          -- 사용자 이름
    USER_NICK VARCHAR2(100) NOT NULL,          -- 사용자 닉네임
    USER_ID VARCHAR2(100) NOT NULL,            -- 사용자 ID
    USER_PWD VARCHAR2(255) NOT NULL,           -- 사용자 비밀번호 (암호화 대비 255자)
    STATUS CHAR(1) DEFAULT 'Y' NOT NULL,       -- 활성화 상태 (기본값 Y)
    
    CONSTRAINT PK_USER PRIMARY KEY (USER_NO)   
);

-- 유저 덱 테이블
CREATE TABLE USER_DECK (
    USER_NO NUMBER NOT NULL,      -- 사용자 계정 번호(PK/FK)
    CARD_NO NUMBER NOT NULL,      -- 카드별 번호(PK/FK)
    LOBBY_NO NUMBER NOT NULL,     -- 로비 번호(PK/FK)
    COUNT NUMBER NOT NULL,        -- 해당 카드의 장수
    
    CONSTRAINT PK_USER_DECK PRIMARY KEY (USER_NO, CARD_NO, LOBBY_NO),
    
    CONSTRAINT FK_DECK_USER FOREIGN KEY (USER_NO) REFERENCES "USER"(USER_NO),
    CONSTRAINT FK_DECK_CARD FOREIGN KEY (CARD_NO) REFERENCES CARD(CARD_NO),
    CONSTRAINT FK_DECK_LOBBY FOREIGN KEY (LOBBY_NO) REFERENCES LOBBY(LOBBY_NO)
);

-- 로비 테이블
CREATE TABLE LOBBY (
    LOBBY_NO NUMBER NOT NULL,              -- 로비 번호(PK)
    USER_NO NUMBER NOT NULL,               -- 사용자 계정 번호(FK)
    STATUS VARCHAR2(100) NOT NULL,         -- 시작전 - 진행중 - 종료 상태

    CONSTRAINT PK_LOBBY PRIMARY KEY (LOBBY_NO),
    
    CONSTRAINT FK_LOBBY_USER FOREIGN KEY (USER_NO) REFERENCES "USER"(USER_NO)
);

-- 로비 참가 인원수 제한
CREATE TABLE LOBBY_JOIN (
    USER_NO NUMBER NOT NULL,      -- 사용자 계정 번호 (FK)
    LOBBY_NO NUMBER NOT NULL,     -- 로비 번호 (FK)

    CONSTRAINT FK_JOIN_USER FOREIGN KEY (USER_NO) REFERENCES "USER"(USER_NO),
    CONSTRAINT FK_JOIN_LOBBY FOREIGN KEY (LOBBY_NO) REFERENCES LOBBY(LOBBY_NO)
);

-- 채팅 테이블
CREATE TABLE CHAT (
    CHAT_NO NUMBER NOT NULL,               -- 채팅 ID 번호 (PK)
    LOBBY_NO NUMBER NOT NULL,              -- 로비 번호 (FK)
    USER_NO NUMBER NOT NULL,               -- 사용자 계정 번호 (FK)
    MESSAGE VARCHAR2(200) NOT NULL,        -- 사용자의 채팅 내용

    CONSTRAINT PK_CHAT PRIMARY KEY (CHAT_NO),
    
    CONSTRAINT FK_CHAT_LOBBY FOREIGN KEY (LOBBY_NO) REFERENCES LOBBY(LOBBY_NO),
    CONSTRAINT FK_CHAT_USER FOREIGN KEY (USER_NO) REFERENCES "USER"(USER_NO)
);

-- 캐릭터 테이블
CREATE TABLE "CHAR" (
    CHAR_NO NUMBER NOT NULL,          -- 캐릭터 번호(PK)
    CHAR_NAME VARCHAR2(100) NOT NULL, -- 캐릭터 이름
    SPEED NUMBER NOT NULL,            -- 턴 순서 결정용 기본 속도
    CARD_RANGE NUMBER NOT NULL,       -- 직업별 카드 번호 범위
    CONSTRAINT PK_CHAR PRIMARY KEY (CHAR_NO)
);

-- 카드도감 테이블 
CREATE TABLE CARD (
    CARD_NO NUMBER NOT NULL,
    CARD_NAME VARCHAR2(100) NOT NULL,
    COST NUMBER NOT NULL,
    EFFECT NUMBER NOT NULL,
    HIT_RANGE NUMBER NOT NULL,
    CARD_DESC VARCHAR2(100) NOT NULL,
    CARD_IMG NUMBER NOT NULL,
    ATK_TYPE NUMBER NOT NULL,
    CONSTRAINT PK_CARD PRIMARY KEY (CARD_NO)
);

-- 지도 테이블
CREATE TABLE MAP (
    MAP_NO NUMBER NOT NULL,
    MAP_NAME VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_MAP PRIMARY KEY (MAP_NO)
);

-- 층 테이블 
CREATE TABLE FLOOR (
    FLOOR_NO NUMBER NOT NULL,
    MAP_NO NUMBER NOT NULL,
    FLOOR_STATUS VARCHAR2(100) NOT NULL, -- 투표 대기중, 진행중 등
    IS_FINAL VARCHAR2(10) DEFAULT 'FALSE' NOT NULL,
    CONSTRAINT PK_FLOOR PRIMARY KEY (FLOOR_NO, MAP_NO),
    CONSTRAINT FK_FLOOR_MAP FOREIGN KEY (MAP_NO) REFERENCES MAP(MAP_NO)
);

-- 지점 테이블
CREATE TABLE NODE (
    NODE_NO NUMBER NOT NULL,
    FLOOR_NO NUMBER NOT NULL,
    MAP_NO NUMBER NOT NULL,
    NODE_TYPE VARCHAR2(100) NOT NULL, -- 전투, 상점, 이벤트
    CONSTRAINT PK_NODE PRIMARY KEY (NODE_NO, FLOOR_NO, MAP_NO),
    CONSTRAINT FK_NODE_FLOOR FOREIGN KEY (FLOOR_NO, MAP_NO) REFERENCES FLOOR(FLOOR_NO, MAP_NO)
);

-- 연결 테이블
CREATE TABLE NODE_CONN (
    CONN_NO NUMBER NOT NULL,
    NODE_NO NUMBER NOT NULL,
    FLOOR_NO NUMBER NOT NULL,
    MAP_NO NUMBER NOT NULL,
    START_NODE NUMBER NOT NULL, -- 출발 장소
    END_NODE NUMBER NOT NULL,   -- 도착 장소
    CONSTRAINT PK_NODE_CONN PRIMARY KEY (CONN_NO, NODE_NO, FLOOR_NO, MAP_NO),
    CONSTRAINT FK_CONN_NODE FOREIGN KEY (NODE_NO, FLOOR_NO, MAP_NO) 
        REFERENCES NODE(NODE_NO, FLOOR_NO, MAP_NO)
);

-- 상점 테이블
CREATE TABLE SHOP (
    NODE_NO NUMBER NOT NULL,
    FLOOR_NO NUMBER NOT NULL,
    MAP_NO NUMBER NOT NULL,
    SHOP_STATUS VARCHAR2(100) DEFAULT 'INACTIVE' NOT NULL, -- ACTIVE, INACTIVE
    CONSTRAINT PK_SHOP PRIMARY KEY (NODE_NO, FLOOR_NO, MAP_NO),
    CONSTRAINT FK_SHOP_NODE FOREIGN KEY (NODE_NO, FLOOR_NO, MAP_NO) 
        REFERENCES NODE(NODE_NO, FLOOR_NO, MAP_NO)
);

-- 이벤트 기능 테이블
CREATE TABLE EVENT_CONTENT (
    EVT_CONTENT_NO NUMBER NOT NULL,
    EVT_CONTENT VARCHAR2(50) NOT NULL, -- 이벤트 기능 코드
    CONSTRAINT PK_EVENT_CONTENT PRIMARY KEY (EVT_CONTENT_NO)
);

-- 이벤트 테이블
CREATE TABLE EVENT (
    EVT_NO NUMBER NOT NULL,
    EVT_CONTENT_NO NUMBER NOT NULL,
    NODE_NO NUMBER NOT NULL,
    FLOOR_NO NUMBER NOT NULL,
    MAP_NO NUMBER NOT NULL,
    EVT_NAME VARCHAR2(100) NOT NULL,
    EVT_DESC VARCHAR2(200) NOT NULL,
    EVT_SELECT NUMBER NOT NULL,        -- 선택지 구별 컬럼
    EVT_SELECT_DESC VARCHAR2(200) NOT NULL, -- 선택지 설명
    CONSTRAINT PK_EVENT PRIMARY KEY (EVT_NO, EVT_CONTENT_NO, NODE_NO, FLOOR_NO, MAP_NO),
    CONSTRAINT FK_EVT_NODE FOREIGN KEY (NODE_NO, FLOOR_NO, MAP_NO) 
        REFERENCES NODE(NODE_NO, FLOOR_NO, MAP_NO),
    CONSTRAINT FK_EVT_TYPE FOREIGN KEY (EVT_CONTENT_NO) 
        REFERENCES EVENT_CONTENT(EVT_CONTENT_NO)
);

-- 던전 테이블
CREATE TABLE DUNGEON (
    DUN_NUM NUMBER NOT NULL,           -- 던전 식별 번호 (PK)
    DUN_NAME VARCHAR2(100) NOT NULL,   -- 인게임 던전 이름
    DUN_CANT NUMBER,                   -- 이동 불가능한 지형 설정
    CONSTRAINT PK_DUNGEON PRIMARY KEY (DUN_NUM)
);

-- 몬스터 공격 테이블
CREATE TABLE MON_ATK (
    MON_ATK_NO NUMBER NOT NULL,        -- 몬스터 공격 패턴 번호 (PK)
    MON_ATK_NAME VARCHAR2(100) NOT NULL, -- 패턴 설명
    MON_EFFECT NUMBER NOT NULL,        -- 수치 계산용 값
    MON_HIT_RANGE NUMBER NOT NULL,     -- 공격 범위 계산용 값
    ATK_TYPE NUMBER NOT NULL,          -- 공격 방식 (FK)
    CONSTRAINT PK_MON_ATK PRIMARY KEY (MON_ATK_NO),
    CONSTRAINT FK_MON_ATK_TYPE FOREIGN KEY (ATK_TYPE) REFERENCES ATK_PATTERN(ATK_TYPE)
);

-- 몬스터 도감 테이블
CREATE TABLE MONSTER (
    MON_NO NUMBER NOT NULL,            -- 몬스터 고유 번호 (PK)
    MON_NAME CHAR(30) NOT NULL,        -- 몬스터 이름
    MON_DIF NUMBER NOT NULL,           -- 난이도 설정값
    MON_SPEED NUMBER NOT NULL,         -- 턴 순서용 속도값
    MON_HP NUMBER NOT NULL,            -- 최대 체력
    MON_EFFECT NUMBER NOT NULL,        -- 기본 효과값 (치유/공격)
    MON_IMG VARCHAR2(250) NOT NULL,    -- 출력할 이미지 경로
    MON_ATK_NO NUMBER NOT NULL,        -- 몬스터 공격 패턴 (FK)
    CONSTRAINT PK_MONSTER PRIMARY KEY (MON_NO),
    CONSTRAINT FK_MON_PATTERN FOREIGN KEY (MON_ATK_NO) REFERENCES MON_ATK(MON_ATK_NO)
);

-- 공격 방식 테이블
CREATE TABLE ATK_PATTERN (
    ATK_TYPE NUMBER NOT NULL,           -- 공격 방식 ID (PK)
    ATK_NAME CHAR(100) NOT NULL,        -- 공격 방식 이름/설명
    
    CONSTRAINT PK_ATK_PATTERN PRIMARY KEY (ATK_TYPE)
);

ALTER TABLE CARD 
ADD CONSTRAINT FK_CARD_ATK_PATTERN 
FOREIGN KEY (ATK_TYPE) REFERENCES ATK_PATTERN (ATK_TYPE);

